services:
  - type: web
    name: iot-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci --omit=dev
    startCommand: node src/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        value: "https://iot-frontend-wkvx.onrender.com" # Update this once frontend is deployed

  - type: web
    name: iot-frontend
    runtime: node
    region: oregon
    plan: free
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: "https://iot-wkvx.onrender.com"
      - key: NODE_ENV
        value: production
